### ISSUE TITLE
Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by KvalheimRacing** [transcranial/atom-transparency#8]
@transcranial Trying to install this on win 10, but I get this;

```
18:32:09 Wed Jul 19 $ ./script/clean && ./script/build
module.js:471
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\atom\script\lib\clean-caches.js:3:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

I did; `npm install -g fs-extra`
Got this; `-- fs-extra@4.0.0`

But did not work.

Additional info;
node; `v6.11.1`
npm; `3.10.10`

Maybe you forgot some to add some dependencies? (fs-extra as a dependencie in the `package.json`, I can't find it there?), or I may be overseeing something here? Did not work for me tough only adding `"fs-extra": "4.0.0",` in `package.json`

**Comment by KvalheimRacing** [comment]
Ok, wrote in correct `fs-extra` version in `script/package.json`, and updated npm to `v5.3.0`. Then it got past this error. Now I am struck at; 
```
child_process.js:504
    throw err;
    ^

Error: spawnSync python ENOENT
    at exports._errnoException (util.js:1018:11)
    at spawnSync (child_process.js:459:20)
    at Object.execFileSync (child_process.js:496:13)
    at verifyPython (C:\atom\script\lib\verify-machine-requirements.js:55:29)
    at module.exports (C:\atom\script\lib\verify-machine-requirements.js:13:5)
    at Object.<anonymous> (C:\atom\script\bootstrap:20:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by KvalheimRacing** [comment]
and now it suddenly is back at the first error. starting to understand that this is a build error, not application stuff..

**Comment by KvalheimRacing** [comment]
closing this, because of build issue. not application issue

**Comment by michaeljsamuels** [comment]
Having identical problem... can you elaborate on the build issue you've identified?

**Comment by KvalheimRacing** [comment]
Sorry, don't remember my conclution, but ended up not building atom, just downloading it.
There was some other dependencies or packages that was missing. Especially I remember downgrading packages to make them work together.
My goal was to make atom transparent, ended up just downloading Glass2k

**Comment by diartkryyeziu** [comment]
npm install
